In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install opencv-contrib-python

  Using cached opencv_contrib_python-4.11.0.86-cp37-abi3-win_amd64.whl.metadata (20 kB)
Using cached opencv_contrib_python-4.11.0.86-cp37-abi3-win_amd64.whl (46.2 MB)
Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install qrcode

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install "qrcode[pil]"

Note: you may need to restart the kernel to use updated packages.


In [17]:
pip install pyqrcode

     ---------------------------------------- 0.0/41.9 kB ? eta -:--:--
     --------- ------------------------------ 10.2/41.9 kB ? eta -:--:--
     -------------------------------------  41.0/41.9 kB 393.8 kB/s eta 0:00:01
     -------------------------------------- 41.9/41.9 kB 406.2 kB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for pyqrcode: filename=PyQRCode-1.2.1-py3-none-any.whl size=36235 sha256=357069fe541ba8e970d900795be9fbcc323067d2bdddca3f1e108dedf666c3df
  Stored in directory: c:\users\admin\appdata\local\pip\cache\wheels\38\e3\f8\8940ce720556414aefb861a143102b931d8327f6eaea5733e8
Successfully built pyqrcode
Note: you may need to restart the kernel to use updated packages.


In [18]:
pip install pypng

   ---------------------------------------- 0.0/58.1 kB ? eta -:--:--
   ------- -------------------------------- 10.2/58.1 kB ? eta -:--:--
   ----------------------------------- ---- 51.2/58.1 kB 660.6 kB/s eta 0:00:01
   ---------------------------------------- 58.1/58.1 kB 613.0 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [6]:
pip install pyzbar

Note: you may need to restart the kernel to use updated packages.


In [5]:
pip install pyzbar[scripts]

  Using cached pyzbar-0.1.9-py2.py3-none-win_amd64.whl.metadata (10 kB)
  Using cached pillow-11.1.0-cp313-cp313-win_amd64.whl.metadata (9.3 kB)
Using cached pillow-11.1.0-cp313-cp313-win_amd64.whl (2.6 MB)
Using cached pyzbar-0.1.9-py2.py3-none-win_amd64.whl (817 kB)
Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install split-image

Note: you may need to restart the kernel to use updated packages.


In [ ]:
import qrcode
# pathList = ['landStraightPath','landCurvePath','waterStraightPath','waterCurvePath',
#             'bearStartPoint','monkeyStartPoint','duckStartPoint','nemoStartPoint',
#             'honeyEndPoint','bananaEndPoint','ducklingsEndPoint','coralEndPoint',
#             'obstacle']
pathList = ['emptyPath']
for i in range(len(pathList)):
    img = qrcode.make(pathList[i])
    type(img)  
    img.save(f"{pathList[i]}.png")

: 

In [ ]:
import numpy as np
pathDict = {
    'landStraightPath': np.array([[0,0,0],[1,1,1],[0,0,0]]),
    'landCurvePath' : np.array([[0,0,0],[0,1,1],[0,1,0]]),
    'waterStraightPath' : np.array([[0,0,0],[6,6,6],[0,0,0]]),
    'waterCurvePath' : np.array([[0,0,0],[0,6,6],[0,6,0]]),
    'bearStartPoint' : np.array([[0,1,0],[1,2,1],[0,1,0]]),
    'monkeyStartPoint' : np.array([[0,1,0],[1,4,1],[0,1,0]]),
    'duckStartPoint' : np.array([[0,1,0],[1,7,1],[0,1,0]]),
    'nemoStartPoint' : np.array([[0,1,0],[1,9,1],[0,1,0]]),
    'honeyEndPoint' : np.array([[0,1,0],[1,3,1],[0,1,0]]),
    'bananaEndPoint' : np.array([[0,1,0],[1,5,1],[0,1,0]]),
    'ducklingsEndPoint' : np.array([[0,1,0],[1,8,1],[0,1,0]]),
    'coralEndPoint' : np.array([[0,1,0],[1,10,1],[0,1,0]]),
    'obstacle' : np.array([[11,11,11],[11,11,11],[11,11,11]])
}

def pathValue(data):
    return(pathDict[data])

print(pathValue('bearStartPoint'))


[[0 1 0]
 [1 2 1]
 [0 1 0]]


In [9]:
import numpy as np
nig = np.array([[0,0,0],[0,1,1],[0,1,0]])
def fixMatrixOrientation(data,direction):
    if direction == 'LEFT':
        data = np.rot90(data, k=3)
    elif direction == 'DOWN':
        data = np.rot90(data, k=2)
    elif direction == 'RIGHT':
        data = np.rot90(data, k=1)
    return data
print(fixMatrixOrientation(nig,"LEFT"))


[[0 0 0]
 [1 1 0]
 [0 1 0]]


In [ ]:
#random image generator for qr testing
import numpy as np
from PIL import Image
import random

QRimages = ['landStraightPath.png','landCurvePath.png','waterStraightPath.png','waterCurvePath.png','bearStartPoint.png','monkeyStartPoint.png','duckStartPoint.png','nemoStart']
rotationAngle = [0,90,180,270]

for j in range(5):
    imgs_row = [Image.open(QRimages[random.randint(0,4)]).rotate(rotationAngle[random.randint(0,3)]) for i in range(5)]

    min_shape = sorted( [(np.sum(i.size), i.size ) for i in imgs_row])[0][1]
    imgs_comb = np.hstack([i.resize(min_shape) for i in imgs_row])
    imgs_comb = Image.fromarray( imgs_comb)
    imgs_comb.save( f'imgRow{j}.jpg' )    

rowImage = [Image.open(f'imgRow{i}.jpg') for i in range(5)]
min_shape = sorted( [(np.sum(i.size), i.size ) for i in rowImage])[0][1]
imgs_comb = np.vstack([i.resize(min_shape) for i in rowImage])
imgs_comb = Image.fromarray( imgs_comb)
imgs_comb.save( 'QRtest.jpg' )

In [ ]:
#random image generator for qr testing + matrix
import numpy as np
from PIL import Image
import random
import os

def pathValue(data):
    if data == 'straightPath':
        return np.array([[0, 0, 0], [1, 1, 1], [0, 0, 0]])
    elif data == 'curvePath':
        return np.array([[0, 0, 0], [0, 1, 1], [0, 1, 0]])
    elif data == 'tPath':
        return np.array([[0, 0, 0], [1, 1, 1], [0, 1, 0]])
    elif data == 'plusPath':
        return np.array([[0, 1, 0], [1, 1, 1], [0, 1, 0]])
    elif data == 'emptyPath':
        return np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
    elif data == 'startPoint':
        return np.array([[0, 1, 0], [1, 2, 1], [0, 1, 0]])
    elif data == 'endPoint':
        return np.array([[0, 1, 0], [1, 3, 1], [0, 1, 0]])
    else:
        return np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
    
def fixMatrixOrientation(data, direction):
    # Return the rotated matrix instead of modifying in-place
    if direction == 'LEFT':
        return np.rot90(data, k=3)
    elif direction == 'DOWN':
        return np.rot90(data, k=2)
    elif direction == 'RIGHT':
        return np.rot90(data, k=1)
    else:  # 'UP' or default
        return data

# Define paths for images
QRimages = ['straightPath.png', 'curvePath.png', 'tPath.png', 'plusPath.png', 'emptyPath.png', 'startPoint.png', 'endPoint.png']
rotationAngle = [0, 90, 180, 270]
rotationDirection = ['UP', 'RIGHT', "DOWN", "LEFT"]

# Initialize the full matrix
fullMatrix = np.zeros((15, 15))

# Generate the QR code grid
row_images = []
for row in range(5):
    imgs_row = []
    
    for col in range(5):
        # Randomly select image and rotation
        randImg = random.randint(0, 6)  
        randAng = random.randint(0, 3)
        
        # Open and rotate image
        try:
            img = Image.open(QRimages[randImg]).rotate(rotationAngle[randAng])
            imgs_row.append(img)
            
            # Get the path matrix and apply rotation
            matrixName = QRimages[randImg][:-4]  # Remove .png extension
            matrix = pathValue(matrixName)
            rotatedMatrix = fixMatrixOrientation(matrix, rotationDirection[randAng])
            
            # Add to the full matrix at the correct position
            fullMatrix[row*3:(row+1)*3, col*3:(col+1)*3] = rotatedMatrix
        except FileNotFoundError:
            print(f"Warning: {QRimages[randImg]} not found. Using a placeholder.")
            # Create a blank white image as placeholder
            img = Image.new('RGB', (100, 100), color='white')
            imgs_row.append(img)
    
    # Combine images horizontally for this row (NO numpy conversion)
    widths, heights = zip(*(i.size for i in imgs_row))
    total_width = sum(widths)
    max_height = max(heights)
    
    # Create a new image with the appropriate size
    new_img = Image.new('RGB', (total_width, max_height))
    
    # Paste each image into the combined image
    x_offset = 0
    for img in imgs_row:
        new_img.paste(img, (x_offset, 0))
        x_offset += img.size[0]
    
    # Save the row image
    new_img.save(f'imgRow{row}.jpg')
    row_images.append(new_img)

# Combine all rows vertically (NO numpy conversion)
widths, heights = zip(*(i.size for i in row_images))
max_width = max(widths)
total_height = sum(heights)

# Create the final image
final_img = Image.new('RGB', (max_width, total_height))

# Paste each row into the final image
y_offset = 0
for img in row_images:
    final_img.paste(img, (0, y_offset))
    y_offset += img.size[1]

# Save the final image
final_img.save('QRtest.jpg')


print(fullMatrix)

[[0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [1. 2. 1. 1. 2. 1. 1. 1. 0. 1. 3. 1. 1. 1. 1.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 1. 3. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 1. 0. 1. 1. 1. 2. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 1. 1. 3. 1. 1. 1. 0. 1. 3. 1. 1. 1. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0.]]


In [ ]:
import matplotlib.image as img
from pyzbar.pyzbar import decode
from split_image import split_image

split_image('QRtest.jpg', 5, 5, False, False)
for i in range(25):
    for barcode in decode(f"QRtest_{i}.jpg"):
        myData = barcode.data.decode('utf-8')
        print(myData)
        print(barcode.orientation)

In [3]:
import matplotlib.image as img
from pyzbar.pyzbar import decode
from PIL import Image, ImageEnhance
import os

# Function to enhance image for better QR detection
def enhance_image(image_path):
    img = Image.open(image_path)
    # Increase contrast
    enhancer = ImageEnhance.Contrast(img)
    img = enhancer.enhance(2.0)
    # Increase brightness if needed
    enhancer = ImageEnhance.Brightness(img)
    img = enhancer.enhance(1.2)
    return img

# Assuming you already have the split images from split_image function
# If split_image is a custom module, make sure it's properly imported
try:
    from split_image import split_image
    # Run the split_image function to divide QRtest.jpg into 5x5 grid
    split_image('SavedCamImage.png', 5, 5, False, False)
    print("Image successfully split into parts")
except ImportError:
    print("Warning: split_image module not found. Assuming images are already split.")
except Exception as e:
    print(f"Error splitting image: {e}")

# Decode each split part
print("Attempting to decode QR codes in each part...")
decoded_count = 0

for i in range(25):
    filename = f"SavedCamImage_{i}.png"
    
    # Check if file exists
    if not os.path.exists(filename):
        print(f"File not found: {filename}")
        continue
    
    try:
        # Try to enhance the image first for better detection
        enhanced_img = enhance_image(filename)
        
        # First try with enhanced image
        barcodes = decode(enhanced_img)
        
        # If that fails, try with original image
        if not barcodes:
            print(f"Enhanced decode failed for {filename}, trying original image...")
            barcodes = decode(Image.open(filename))
        
        if barcodes:
            for barcode in barcodes:
                try:
                    myData = barcode.data.decode('utf-8')
                    print(f"Part {i}: Data={myData}, Orientation={barcode.orientation}")
                    decoded_count += 1
                except Exception as e:
                    print(f"Error decoding data in {filename}: {e}")
        else:
            print(f"No QR code detected in {filename}")
            
    except Exception as e:
        print(f"Error processing {filename}: {e}")

print(f"\nSummary: Successfully decoded {decoded_count} QR codes out of 25 parts")

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
import cv2
import numpy as np
from pyzbar.pyzbar import decode




cap= cv2.VideoCapture(0)

while True:
    ret, img = cap.read()
    img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img_gray = cv2.bitwise_not(img_gray)
    for barcode in decode(img_gray):
        myData = barcode.data.decode('utf-8')
        print(myData)
        print(barcode.orientation)
    cv2.imshow('Camera',img_gray)
   
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

error: OpenCV(4.11.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:199: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


: 

In [2]:
import cv2
import numpy as np
from pyzbar.pyzbar import decode

cap = cv2.VideoCapture(0)

while True:
    ret, img = cap.read()
    if not ret:
        continue  # Skip frame if camera fails to capture
    
    img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img_gray = cv2.bitwise_not(img_gray)
    for barcode in decode(img_gray):  
        myData = barcode.data.decode('utf-8')
        print(f"Decoded Data: {myData}")
        
        # Draw bounding box around barcode
        points = barcode.polygon
        if len(points) == 4:
            pts = np.array(points, np.int32)
            pts = pts.reshape((-1, 1, 2))
            cv2.polylines(img, [pts], True, (0, 255, 0), 2)
        
        # Put text above barcode
        rect = barcode.orientation
        cv2.putText(img, myData, (rect, rect.top - 10), 
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

    cv2.imshow('Barcode Scanner', img_gray)
   
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()


In [ ]:
import cv2
import numpy as np


image_path = "Img Dump/tapedTest.png"
image = cv2.imread(image_path)
hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

# Define the lower and upper bounds for red color (adjust if needed)
lower_red1 = np.array([0, 120, 100])
upper_red1 = np.array([10, 255, 255])
lower_red2 = np.array([170, 120, 100])
upper_red2 = np.array([180, 255, 255])


mask1 = cv2.inRange(hsv, lower_red1, upper_red1)
mask2 = cv2.inRange(hsv, lower_red2, upper_red2)
mask = mask1 + mask2


contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# Find the largest red contour (assuming it's the border)
contours = sorted(contours, key=cv2.contourArea, reverse=True)
if contours:
    x, y, w, h = cv2.boundingRect(contours[0])

    # Crop the inner area
    cropped_image = image[y:y+h, x:x+w]

    # Save or display the cropped image
    cropped_path = "Img Dump/croppedQR.png"
    cv2.imwrite(cropped_path, cropped_image)
    print(f"Cropped image saved to: {cropped_path}")
else:
    print("No red border detected")

Cropped image saved to: Img Dump/croppedQR.png


In [ ]:
import matplotlib.image as img
from pyzbar.pyzbar import decode
from split_image import split_image
import cv2
import numpy as np

image_path = "Img Dump/tapedTest.png"
image = cv2.imread(image_path)
# Convert to HSV color space
hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

# Define the lower and upper bounds for red color (adjust if needed)
lower_red1 = np.array([0, 120, 100])
upper_red1 = np.array([10, 255, 255])
lower_red2 = np.array([170, 120, 100])
upper_red2 = np.array([180, 255, 255])


mask1 = cv2.inRange(hsv, lower_red1, upper_red1)
mask2 = cv2.inRange(hsv, lower_red2, upper_red2)
mask = mask1 + mask2
contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)


contours = sorted(contours, key=cv2.contourArea, reverse=True)
if contours:
    x, y, w, h = cv2.boundingRect(contours[0])
    cropped_image = image[y:y+h, x:x+w]
    cropped_path = "Img Dump/croppedQR.png"
    cv2.imwrite(cropped_path, cropped_image)
    print(f"Cropped image saved to: {cropped_path}")

    
    split_image(cropped_path, 5, 5, False, False)
    for i in range(25):
        img = cv2.imread(f'croppedQR_{i}.png')
        for barcode in decode(img):
            myData = barcode.data.decode('utf-8')
            print(myData)
            print(barcode.orientation)
else:
    print("No red border detected!")



In [ ]:
import matplotlib.image as img
from pyzbar.pyzbar import decode
from split_image import split_image
import cv2
import numpy as np
import os

cap = cv2.VideoCapture(0)

lower_red1 = np.array([0, 120, 100])
upper_red1 = np.array([10, 255, 255])
lower_red2 = np.array([170, 120, 100])
upper_red2 = np.array([180, 255, 255])

while True:
    ret, image = cap.read()
    cv2.imshow("cap",image)
    
    if len(decode(image))!=0:
        hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
        image_path = "Img Dump/Cap Save/capRead.png"
        cv2.imwrite(os.path.join(image_path , 'capRead.jpg'), image)

        mask1 = cv2.inRange(hsv, lower_red1, upper_red1)
        mask2 = cv2.inRange(hsv, lower_red2, upper_red2)
        mask = mask1 + mask2
        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        contours = sorted(contours, key=cv2.contourArea, reverse=True)
        x, y, w, h = cv2.boundingRect(contours[0])
        cropped_image = image[y:y+h, x:x+w]
        cropped_path = "Img Dump/croppedQR.png"
        cv2.imwrite(cropped_path, cropped_image)
        print(f"Cropped image saved to: {cropped_path}")

        split_image(cropped_path, 5, 5, False, False)
        for i in range(25):
            img = cv2.imread(f'croppedQR_{i}.png')
            for barcode in decode(img):
                myData = barcode.data.decode('utf-8')
                print(myData)
                print(barcode.orientation)
        break
    else:
        print("No red border detected!")

cap.release()
cv2.destroyAllWindows()

In [ ]:
import matplotlib.image as img
from pyzbar.pyzbar import decode
from split_image import split_image
import cv2
import numpy as np
import os

# Create directories if they don't exist
os.makedirs("Img Dump/Cap Save", exist_ok=True)

cap = cv2.VideoCapture(0)
if not cap.isOpened():
    print("Error: Could not open camera.")
    exit()

# HSV range for red color (red wraps around in HSV, so we need two ranges)
lower_red1 = np.array([0, 120, 100])
upper_red1 = np.array([10, 255, 255])
lower_red2 = np.array([170, 120, 100])
upper_red2 = np.array([180, 255, 255])

output_dir = "Img Dump"

while True:
    ret, image = cap.read()
    if not ret:
        print("Failed to grab frame")
        break
        
    cv2.imshow("cap", image)
    
    # Check for QR codes in the image
    detected_codes = decode(image)
    numQR = len(detected_codes)
    print(numQR)

    if numQR >= 20:
        # Save the original captured image
        cap_save_path = os.path.join(output_dir, "Cap Save", "capRead.jpg")
        cv2.imwrite(cap_save_path, image)
        
        # Convert to HSV for red color detection
        hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
        
        # Create mask for red color
        mask1 = cv2.inRange(hsv, lower_red1, upper_red1)
        mask2 = cv2.inRange(hsv, lower_red2, upper_red2)
        mask = mask1 + mask2
        
        # Find contours of red regions
        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        
        if contours:
            # Sort contours by area and get the largest one
            contours = sorted(contours, key=cv2.contourArea, reverse=True)
            x, y, w, h = cv2.boundingRect(contours[0])
            
            # Crop image to the red border
            cropped_image = image[y:y+h, x:x+w]
            cropped_path = os.path.join(output_dir, "croppedQR.png")
            cv2.imwrite(cropped_path, cropped_image)
            print(f"Cropped image saved to: {cropped_path}")
            
            # Split the cropped image into 5x5 grid
            # split_dir = os.path.join(output_dir, "split")
            # os.makedirs(split_dir, exist_ok=True)
            
            # Make sure split_image function saves to the correct directory
            split_image(cropped_path, 5, 5, False, False)
            
            # Process each split image
            for i in range(25):
                split_img_path = os.path.join(f'croppedQR_{i}.png')
                if os.path.exists(split_img_path):
                    img = cv2.imread(f'croppedQR_{i}.png')
                    if img is not None:
                        for barcode in decode(img):
                            myData = barcode.data.decode('utf-8')
                            print(f"QR Code data from part {i}: {myData}")
                            print(f"Orientation: {barcode.orientation}")
                    else:
                        print(f"Could not read split image {i}")
                else:
                    print(f"Split image {i} does not exist at {split_img_path}")
            
            # Break the loop after processing
            break
        else:
            print("Red border detected but no valid contours found")
    else:
        print("No QR codes detected in frame")
    
    # Exit if 'q' is pressed
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR 

In [ ]:
import matplotlib.image as img
from pyzbar.pyzbar import decode
from split_image import split_image
import cv2
import numpy as np
import os

# Create directories if they don't exist
os.makedirs("Img Dump/Cap Save", exist_ok=True)

cap = cv2.VideoCapture(0)
# address = "https://10.197.188.32:8080/video"
# cap.open(address)

if not cap.isOpened():
    print("Error: Could not open camera.")
    exit()

# HSV range for red color (red wraps around in HSV, so we need two ranges)
lower_red1 = np.array([0, 120, 100])
upper_red1 = np.array([10, 255, 255])
lower_red2 = np.array([170, 120, 100])
upper_red2 = np.array([180, 255, 255])

output_dir = "Img Dump"

while True:
    ret, image = cap.read()
    if not ret:
        print("Failed to grab frame")
        break
        
    cv2.imshow("cap", image)
    
    # Check for QR codes in the image
    detected_codes = decode(image)
    numQR = len(detected_codes)
    print(numQR)

    if numQR >= 15:
        # Save the original captured image
        cap_save_path = os.path.join(output_dir, "Cap Save", "capRead.jpg")
        cv2.imwrite(cap_save_path, image)
        
        # Convert to HSV for red color detection
        hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
        
        # Create mask for red color
        mask1 = cv2.inRange(hsv, lower_red1, upper_red1)
        mask2 = cv2.inRange(hsv, lower_red2, upper_red2)
        mask = mask1 + mask2
        
        # Find contours of red regions
        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        
        if contours:
            # Sort contours by area and get the largest one
            contours = sorted(contours, key=cv2.contourArea, reverse=True)
            x, y, w, h = cv2.boundingRect(contours[0])
            
            # Calculate border thickness (estimate)
            # You can adjust these values based on your specific red border thickness
            border_thickness = 10  # pixels
            
            # Crop image excluding the red border
            inner_x = x + border_thickness
            inner_y = y + border_thickness
            inner_w = w - (2 * border_thickness)
            inner_h = h - (2 * border_thickness)
            
            # Ensure we don't have negative dimensions
            if inner_w > 0 and inner_h > 0:
                cropped_image = image[inner_y:inner_y+inner_h, inner_x:inner_x+inner_w]
                cropped_path = os.path.join(output_dir, "croppedQR.png")
                cv2.imwrite(cropped_path, cropped_image)
                print(f"Cropped image saved to: {cropped_path}")
                
                # Split the cropped image into 5x5 grid
                # split_dir = os.path.join(output_dir, "split")
                # os.makedirs(split_dir, exist_ok=True)
                
                # Make sure split_image function saves to the correct directory
                split_image(cropped_path, 5, 5, False, False)
                
                # Process each split image
                for i in range(25):
                    split_img_path = os.path.join(f'croppedQR_{i}.png')
                    if os.path.exists(split_img_path):
                        img = cv2.imread(f'croppedQR_{i}.png')
                        if img is not None:
                            for barcode in decode(img):
                                myData = barcode.data.decode('utf-8')
                                print(f"QR Code data from part {i}: {myData}")
                                print(f"Orientation: {barcode.orientation}")
                        else:
                            print(f"Could not read split image {i}")
                    else:
                        print(f"Split image {i} does not exist at {split_img_path}")
                
                # Break the loop after processing
                break
            else:
                print("Border detection resulted in invalid dimensions")
        else:
            print("Red border detected but no valid contours found")
    else:
        print("No QR codes detected in frame")
    
    # Exit if 'q' is pressed
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR codes detected in frame
0
No QR 

In [2]:
import numpy as np
from pyzbar.pyzbar import decode
import cv2

# Read image
img = cv2.imread('nigga.png')

# Decode the barcode
decoded_objects = decode(img)

# Loop through decoded barcodes
for obj in decoded_objects:
    print("Data:", obj.data.decode('utf-8'))
    print(obj.orientation)
    print(len(decoded_objects))

Data: nigga
UP
1
